language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

install:
    - pip install -q coveralls
    - pip install -q tox

after_success:
  - coverage combine
  - coveralls

branches:
  only:
    - master

script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-django${DJANGO_VERSION},docs
